Repository Proffet78/KR_TRPO_Modern, pull requests merged in 2020-07, with the labels that each got.

#43 Update styles.css в LK
  LK/css/styles.css
  index_LK.html
Labels: SPRINT3, bug

#62 Добавил форму регистрации события
  EvenReg.html
Labels: Registration event, development, form

#65 Регистрация пользователя на DJANGO
  .gitignore
  DJANGO/DJANGO/__init__.py
  DJANGO/DJANGO/__pycache__/__init__.cpython-38.pyc
  DJANGO/DJANGO/__pycache__/settings.cpython-38.pyc
  DJANGO/DJANGO/__pycache__/urls.cpython-38.pyc
  DJANGO/DJANGO/__pycache__/wsgi.cpython-38.pyc
  DJANGO/DJANGO/apps/siteDJ/__pycache__/__init__.cpython-38.pyc
  DJANGO/DJANGO/apps/siteDJ/__pycache__/urls.cpython-38.pyc
  DJANGO/DJANGO/apps/siteDJ/__pycache__/views.cpython-38.pyc
  DJANGO/DJANGO/apps/siteDJ/models.py
  DJANGO/DJANGO/apps/siteDJ/urls.py
  DJANGO/DJANGO/apps/siteDJ/views.py
  DJANGO/DJANGO/static/LK/bootstrap/fonts/glyphicons-halflings-regular.eot
  DJANGO/DJANGO/static/LK/bootstrap/fonts/glyphicons-halflings-regular.ttf
  DJANGO/DJANGO/static/LK/bootstrap/fonts/glyphicons-halflings-regular.woff
  DJANGO/DJANGO/static/LK/bootstrap/fonts/glyphicons-halflings-regular.woff2
  DJANGO/DJANGO/static/LK/font-awesome/fonts/FontAwesome.otf
  DJANGO/DJANGO/static/LK/font-awesome/fonts/fontawesome-webfont.eot
  DJANGO/DJANGO/static/LK/font-awesome/fonts/fontawesome-webfont.svg
  DJANGO/DJANGO/static/LK/font-awesome/fonts/fontawesome-webfont.ttf
  DJANGO/DJANGO/static/LK/font-awesome/fonts/fontawesome-webfont.woff
  DJANGO/DJANGO/static/LK/images/blue-bg.jpg
  DJANGO/DJANGO/static/OS/css/registr.css
  DJANGO/DJANGO/static/OS/css/style.css
  DJANGO/DJANGO/static/OS/img/header-bg.jpg
  DJANGO/DJANGO/static/OS/img/portfolio-bg.jpg
  DJANGO/DJANGO/static/OS/js/main.js
  DJANGO/DJANGO/static/OS/lib/bootstrap/fonts/glyphicons-halflings-regular.eot
  DJANGO/DJANGO/static/OS/lib/bootstrap/fonts/glyphicons-halflings-regular.svg
  DJANGO/DJANGO/static/OS/lib/bootstrap/fonts/glyphicons-halflings-regular.ttf
  DJANGO/DJANGO/static/OS/lib/bootstrap/fonts/glyphicons-halflings-regular.woff
  DJANGO/DJANGO/static/OS/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2
  DJANGO/DJANGO/static/OS/lib/font-awesome/fonts/FontAwesome.otf
  DJANGO/DJANGO/static/OS/lib/font-awesome/fonts/fontawesome-webfont.eot
  DJANGO/DJANGO/static/OS/lib/font-awesome/fonts/fontawesome-webfont.svg
  DJANGO/DJANGO/static/OS/lib/font-awesome/fonts/fontawesome-webfont.ttf
  DJANGO/DJANGO/static/OS/lib/font-awesome/fonts/fontawesome-webfont.woff
  DJANGO/DJANGO/tamplates/base.html
  DJANGO/DJANGO/tamplates/siteDJ/lk.html
  DJANGO/DJANGO/tamplates/siteDJ/main.html
  DJANGO/db.sqlite3
Labels: SPRINT4

#72 Перевод формы регистрации события на django
  DJANGO/DJANGO/tamplates/siteDJ/EvenReg.html
  DJANGO/DJANGO/tamplates/siteDJ/main.html
  index_OS.html
Labels: bug

#71 Исправление багов при переводе на DJANGO
  DJANGO/DJANGO/static/OS/css/style.css
Labels: bug

#75 Залить ERD Project в репозиторий
  Diagram/ERD/ERD project.svg
Labels: Er diagram

#78 Разработал UML диаграмму для проекта
  Diagram/UML/UML_Diagram.svg
Labels: Diagram, UML-diagramm
